baseURL = 'https://blog.dannysun.site'
languageCode = 'zh'
title = "S先生的笔记📒"
paginate = 10
theme = 'maverick'

[permalinks]
pages = "/:slug"

[params]
logo = '/images/favicon.png'
description = "A minimal hugo theme focus on content"
author = 'Daniel Sun'
custom_css = ["css/styles.css"]

[params.comments]
githubRepo = 'dannysunyu/myblog-site'
theme = 'github-light'

[menu]
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = "-110"
[[menu.main]]
identifier = "posts"
name = "Post"
url = "/posts/"
weight = -200
[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = -300

[markup]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
hl_inline = false
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
noHl = false
style = 'monokailight'
tabWidth = 4

[taxonomies]
tags = "tags"
categories = "categories"

[outputs]
home = ["HTML", "RSS", "JSON"]
section = ["HTML"]

[outputFormats.RSS]
mediatype = "application/rss"
baseName = "atom"

[outputFormats.JSON]
mediatype = "application/json"
baseName = "feed"

ignoreErrors = ["error-remote-getjson"]
